// <auto-generated />
using System;
using CarBooking.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarBooking.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20250411203639_Add_Comments")]
    partial class Add_Comments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarBooking.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Spaces")
                        .HasColumnType("integer");

                    b.Property<int>("Transmission")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 0,
                            Img = "https://static.lada.ru/images/v6/cars/configurator/granta/sedan.webp",
                            Name = "LADA Granta",
                            Price = 99m,
                            Spaces = 3,
                            Transmission = 0
                        },
                        new
                        {
                            Id = 2,
                            Category = 2,
                            Img = "https://static.lada.ru/images/v6/cars/configurator/granta/liftback.webp",
                            Name = "LADA Granta",
                            Price = 100m,
                            Spaces = 2,
                            Transmission = 0
                        },
                        new
                        {
                            Id = 3,
                            Category = 3,
                            Img = "https://static.lada.ru/images/v6/cars/configurator/granta/cross.webp",
                            Name = "LADA Granta",
                            Price = 80m,
                            Spaces = 5,
                            Transmission = 1
                        },
                        new
                        {
                            Id = 4,
                            Category = 0,
                            Img = "https://static.lada.ru/images/v6/cars/configurator/vesta_new/sedan.webp",
                            Name = "LADA Vesta",
                            Price = 50m,
                            Spaces = 4,
                            Transmission = 0
                        },
                        new
                        {
                            Id = 5,
                            Category = 1,
                            Img = "https://static.lada.ru/images/v6/cars/configurator/vesta_new/cross.webp",
                            Name = "LADA Vesta",
                            Price = 120m,
                            Spaces = 4,
                            Transmission = 1
                        },
                        new
                        {
                            Id = 6,
                            Category = 4,
                            Img = "https://static.lada.ru/images/v6/cars/configurator/vesta_new/sw.webp",
                            Name = "LADA Vesta",
                            Price = 100m,
                            Spaces = 5,
                            Transmission = 1
                        },
                        new
                        {
                            Id = 7,
                            Category = 5,
                            Img = "https://static.lada.ru/images/v6/cars/configurator/vesta_new/sedan.webp",
                            Name = "LADA Largus",
                            Price = 40m,
                            Spaces = 5,
                            Transmission = 0
                        },
                        new
                        {
                            Id = 8,
                            Category = 1,
                            Img = "https://static.lada.ru/images/v6/cars/configurator/vesta_new/cross.webp",
                            Name = "LADA Largus",
                            Price = 40m,
                            Spaces = 4,
                            Transmission = 1
                        },
                        new
                        {
                            Id = 9,
                            Category = 3,
                            Img = "https://static.lada.ru/images/v6/cars/configurator/vesta_new/sportline.webp",
                            Name = "LADA Vesta",
                            Price = 100m,
                            Spaces = 5,
                            Transmission = 1
                        },
                        new
                        {
                            Id = 10,
                            Category = 3,
                            Img = "https://static.lada.ru/images/v6/cars/configurator/granta/sportline.webp",
                            Name = "LADA Granta",
                            Price = 120m,
                            Spaces = 5,
                            Transmission = 0
                        });
                });

            modelBuilder.Entity("CarBooking.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 1,
                            Date = new DateTime(2025, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Img = "/images/tagir.jpg",
                            Name = "Tagir Akhmetshin",
                            Position = "Senior Backend Developer",
                            Text = "Отличная машина, лучше всех. Мне очень нравится"
                        },
                        new
                        {
                            Id = 2,
                            CarId = 1,
                            Date = new DateTime(2025, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Img = "/images/vlada.jpg",
                            Name = "Vlada Yakusheva",
                            Position = "Senior Frontend Developer",
                            Text = "Супер машина, все удочки помещаются"
                        },
                        new
                        {
                            Id = 3,
                            CarId = 2,
                            Date = new DateTime(2025, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Img = "https://camo.githubusercontent.com/619e60801937aeb64755546251df3a4ffe1a786a38e91ee33d2c81eccca9685e/68747470733a2f2f617661746172732e6d64732e79616e6465782e6e65742f693f69643d34316661666336623632636363313037623761666233396435376266633564665f6c2d373130363839392d696d616765732d7468756d6273266e3d3133",
                            Name = "Ivan Ivanov",
                            Position = "Developer",
                            Text = "Really good car"
                        },
                        new
                        {
                            Id = 4,
                            CarId = 3,
                            Date = new DateTime(2025, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Img = "https://camo.githubusercontent.com/619e60801937aeb64755546251df3a4ffe1a786a38e91ee33d2c81eccca9685e/68747470733a2f2f617661746172732e6d64732e79616e6465782e6e65742f693f69643d34316661666336623632636363313037623761666233396435376266633564665f6c2d373130363839392d696d616765732d7468756d6273266e3d3133",
                            Name = "Ivan Ivanov",
                            Position = "Developer",
                            Text = "Really good car"
                        },
                        new
                        {
                            Id = 5,
                            CarId = 4,
                            Date = new DateTime(2025, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Img = "https://camo.githubusercontent.com/619e60801937aeb64755546251df3a4ffe1a786a38e91ee33d2c81eccca9685e/68747470733a2f2f617661746172732e6d64732e79616e6465782e6e65742f693f69643d34316661666336623632636363313037623761666233396435376266633564665f6c2d373130363839392d696d616765732d7468756d6273266e3d3133",
                            Name = "Ivan Ivanov",
                            Position = "Developer",
                            Text = "Really good car"
                        },
                        new
                        {
                            Id = 6,
                            CarId = 5,
                            Date = new DateTime(2025, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Img = "https://camo.githubusercontent.com/619e60801937aeb64755546251df3a4ffe1a786a38e91ee33d2c81eccca9685e/68747470733a2f2f617661746172732e6d64732e79616e6465782e6e65742f693f69643d34316661666336623632636363313037623761666233396435376266633564665f6c2d373130363839392d696d616765732d7468756d6273266e3d3133",
                            Name = "Ivan Ivanov",
                            Position = "Developer",
                            Text = "Really good car"
                        },
                        new
                        {
                            Id = 7,
                            CarId = 6,
                            Date = new DateTime(2025, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Img = "https://camo.githubusercontent.com/619e60801937aeb64755546251df3a4ffe1a786a38e91ee33d2c81eccca9685e/68747470733a2f2f617661746172732e6d64732e79616e6465782e6e65742f693f69643d34316661666336623632636363313037623761666233396435376266633564665f6c2d373130363839392d696d616765732d7468756d6273266e3d3133",
                            Name = "Ivan Ivanov",
                            Position = "Developer",
                            Text = "Really good car"
                        },
                        new
                        {
                            Id = 8,
                            CarId = 7,
                            Date = new DateTime(2025, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Img = "https://camo.githubusercontent.com/619e60801937aeb64755546251df3a4ffe1a786a38e91ee33d2c81eccca9685e/68747470733a2f2f617661746172732e6d64732e79616e6465782e6e65742f693f69643d34316661666336623632636363313037623761666233396435376266633564665f6c2d373130363839392d696d616765732d7468756d6273266e3d3133",
                            Name = "Ivan Ivanov",
                            Position = "Developer",
                            Text = "Really good car"
                        },
                        new
                        {
                            Id = 9,
                            CarId = 8,
                            Date = new DateTime(2025, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Img = "https://camo.githubusercontent.com/619e60801937aeb64755546251df3a4ffe1a786a38e91ee33d2c81eccca9685e/68747470733a2f2f617661746172732e6d64732e79616e6465782e6e65742f693f69643d34316661666336623632636363313037623761666233396435376266633564665f6c2d373130363839392d696d616765732d7468756d6273266e3d3133",
                            Name = "Ivan Ivanov",
                            Position = "Developer",
                            Text = "Really good car"
                        },
                        new
                        {
                            Id = 10,
                            CarId = 9,
                            Date = new DateTime(2025, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Img = "https://camo.githubusercontent.com/619e60801937aeb64755546251df3a4ffe1a786a38e91ee33d2c81eccca9685e/68747470733a2f2f617661746172732e6d64732e79616e6465782e6e65742f693f69643d34316661666336623632636363313037623761666233396435376266633564665f6c2d373130363839392d696d616765732d7468756d6273266e3d3133",
                            Name = "Ivan Ivanov",
                            Position = "Developer",
                            Text = "Really good car"
                        },
                        new
                        {
                            Id = 11,
                            CarId = 10,
                            Date = new DateTime(2025, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Img = "https://camo.githubusercontent.com/619e60801937aeb64755546251df3a4ffe1a786a38e91ee33d2c81eccca9685e/68747470733a2f2f617661746172732e6d64732e79616e6465782e6e65742f693f69643d34316661666336623632636363313037623761666233396435376266633564665f6c2d373130363839392d696d616765732d7468756d6273266e3d3133",
                            Name = "Ivan Ivanov",
                            Position = "Developer",
                            Text = "Really good car"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
