// <auto-generated />
using CarBooking.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarBooking.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20250411201333_Add_Cars")]
    partial class Add_Cars
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarBooking.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Spaces")
                        .HasColumnType("integer");

                    b.Property<int>("Transmission")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 0,
                            Img = "https://static.lada.ru/images/v6/cars/configurator/granta/sedan.webp",
                            Name = "LADA Granta",
                            Price = 99m,
                            Spaces = 3,
                            Transmission = 0
                        },
                        new
                        {
                            Id = 2,
                            Category = 2,
                            Img = "https://static.lada.ru/images/v6/cars/configurator/granta/liftback.webp",
                            Name = "LADA Granta",
                            Price = 100m,
                            Spaces = 2,
                            Transmission = 0
                        },
                        new
                        {
                            Id = 3,
                            Category = 3,
                            Img = "https://static.lada.ru/images/v6/cars/configurator/granta/cross.webp",
                            Name = "LADA Granta",
                            Price = 80m,
                            Spaces = 5,
                            Transmission = 1
                        },
                        new
                        {
                            Id = 4,
                            Category = 0,
                            Img = "https://static.lada.ru/images/v6/cars/configurator/vesta_new/sedan.webp",
                            Name = "LADA Vesta",
                            Price = 50m,
                            Spaces = 4,
                            Transmission = 0
                        },
                        new
                        {
                            Id = 5,
                            Category = 1,
                            Img = "https://static.lada.ru/images/v6/cars/configurator/vesta_new/cross.webp",
                            Name = "LADA Vesta",
                            Price = 120m,
                            Spaces = 4,
                            Transmission = 1
                        },
                        new
                        {
                            Id = 6,
                            Category = 4,
                            Img = "https://static.lada.ru/images/v6/cars/configurator/vesta_new/sw.webp",
                            Name = "LADA Vesta",
                            Price = 100m,
                            Spaces = 5,
                            Transmission = 1
                        },
                        new
                        {
                            Id = 7,
                            Category = 5,
                            Img = "https://static.lada.ru/images/v6/cars/configurator/vesta_new/sedan.webp",
                            Name = "LADA Largus",
                            Price = 40m,
                            Spaces = 5,
                            Transmission = 0
                        },
                        new
                        {
                            Id = 8,
                            Category = 1,
                            Img = "https://static.lada.ru/images/v6/cars/configurator/vesta_new/cross.webp",
                            Name = "LADA Largus",
                            Price = 40m,
                            Spaces = 4,
                            Transmission = 1
                        },
                        new
                        {
                            Id = 9,
                            Category = 3,
                            Img = "https://static.lada.ru/images/v6/cars/configurator/vesta_new/sportline.webp",
                            Name = "LADA Vesta",
                            Price = 100m,
                            Spaces = 5,
                            Transmission = 1
                        },
                        new
                        {
                            Id = 10,
                            Category = 3,
                            Img = "https://static.lada.ru/images/v6/cars/configurator/granta/sportline.webp",
                            Name = "LADA Granta",
                            Price = 120m,
                            Spaces = 5,
                            Transmission = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
